### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by becker-asano-hdm** [MeqdadDev/teachable-machine#1]
I am following the instruction in the Readme.md with "!pip install teachable-machine", which runs succesfully. But then the line

> from teachable_machine import TeachableMachine

fails with:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-69589265f811> in <module>
      1 get_ipython().system('pip install teachable-machine')
      2 
----> 3 from teachable_machine import TeachableMachine
      4 
      5 my_model = TeachableMachine(model_path='keras_model.h5', model_type='h5')

ModuleNotFoundError: No module named 'teachable_machine'
```

Complete Jupyter notebook (Python 3.7):

```
!pip install teachable-machine

from teachable_machine import TeachableMachine

my_model = TeachableMachine(model_path='keras_model.h5', model_type='h5')

img_path = 'images/my_image.jpg'

result = my_model.classify_image(img_path)

print('highest_class_id:', result['highest_class_id'])
print('all_predictions:', result['all_predictions'])
```

**Comment by MeqdadDev** [comment]
Hi @becker-asano-hdm 
I've noticed that recently, this issue will be resolved ASAP (it is related to the settings of publishing packages on PyPI, not the source code).

As a quick solution, you can download the module itself from this repo, and then import it in your file.

Thanks for your note.

**Comment by MeqdadDev** [comment]
Hi @becker-asano-hdm 

This issue is fixed now, you can try again.
